version: '2.2'

services:
  db: 
    container_name: 'kki-log_database'
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "local"
      POSTGRES_PASSWORD: "local"
      POSTGRES_DB: "local"
    volumes:
      - ./db/data/:/var/lib/postgresql/data
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql